module.exports = {
    FB_PAGE_TOKEN: 'EAANcmYcKlRwBAOeLEbdgJPrMD26ITu9Jv86IL2A4Nynb0s57z3RhMLym3ZC30geG45nERlMv6T3VOqZAOqXoTVi1PUZCOxb6HO2JVWku6CMSiTZBqhuqZBu5xXbr1GjsDbOySv5Lda80vupigdrTjTNN95BfCpQaP8TZAZCMJRegQZDZD',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
};
